[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Herberth Leão <dev@herberthleao.com>"]
edition = "2021"

description = "A guessing game."
license = "MIT"
repository = "https://github.com/herberthleao/rust-book-exercises"

[dependencies]
rand = "0.8.5"